name: Testing gitversion

on:
  workflow_dispatch:
  push:

jobs:

  metadata_raw-version:
    name: Determine the intended website version
    runs-on: ubuntu-latest
    outputs:
      raw-version: ${{ steps.gitversion.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"

  metadata_go-version:
    name: "Determine Go toolchain version"
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Determine Go version
        id: version
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "::set-output name=go-version::$(cat .go-version)"