name: Build AS207414 website packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - release/*
    tags:
      - v*

jobs:
  get-website-version:
    name: Determine the intended website version
    runs-on: ubuntu-latest
    outputs:
      website-version: ${{ steps.get-website-version.outputs.product-version }}

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git descibe
        id: git-describe
        run: |
          git describe --first-parent
          echo "::set-output name=raw-version::$(git describe --first-parent)"

      - name: Decide version number
        id: get-website-version
        shell: bash
        env:
          RAW_VERSION: ${{ steps.git-describe.outputs.raw-version }}
        run: |
          echo "::set-output name=website-version::${RAW_VERSION#v}"

  get-go-version:
    name: "Determine Go toolchain version"
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Determine Go version
        id: get-go-version
        # We use .go-version as our source of truth for current Go
        # version, because "goenv" can react to it automatically.
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "::set-output name=go-version::$(cat .go-version)"
